### ISSUE TITLE
Verbetering [DO3]: maak een nieuwe component/package aan voor je trainer

### ISSUE THREAD

**Issue by arothuis-hu** [EtienneHosman/cisq1-lingo#5]
Je hebt nu alle objecten ondergebracht in dezelfde component (in package `nl.hu.lingo.words`). 

Maak een nieuwe package aan `nl.hu.lingo.trainer` met de lagen `presentation`, `application`, `domain` en `data`. Verplaats (met IntelliJ) de juiste concepten in de juiste lagen.

**Comment by EtienneHosman** [comment]
fixed
